### ISSUE TITLE
A naive correction for ltype.c casting

### ISSUE THREAD

**Issue by stefanos82** [lemon-lang/lemon#11]
In https://github.com/lemon-lang/lemon/blob/master/src/ltype.c#L34, you forgot to use `cast(self)` that you have defined 4 lines above and typecast-ed `self` the traditional way.

**Comment by zhicheng** [comment]
ha, nice catch.but not a real issues.I probably not change this time,maybe when this file need be fix I'll change it.Thanks anyway.

if you has any question in reading source, feel free ask me in mailling-list.

**Comment by stefanos82** [comment]
I have asked already two questions in mailing list.
