### ISSUE TITLE
history support

### ISSUE THREAD

**Issue by 2000jedi** [lemon-lang/lemon#21]
Lemon does not support retrieving the history via arrow keys. Is it possible to implement GNU Readline to support shell-like shortcuts?

![lemon-issue](https://user-images.githubusercontent.com/8778370/32763265-9a5c0bf8-c939-11e7-9119-2f65f4591e30.jpeg)

**Comment by zhicheng** [comment]
this shell will not provide history or shortcut support, because that will broken ANSI C rule, I may implementation a new fully feature independent shell in future.
