### ISSUE TITLE
possible bug in os.open('file','r') and os.open('file','w')

### ISSUE THREAD

**Issue by 2000jedi** [lemon-lang/lemon#22]
In /lib/os.c:
* line 44, should be 'r=1;' instead of 'a=1;'
* line 47, I expect it to be 'w=1;r=1;'. Flag 'w' is sufficient to state O_RDWR. (Could be my fault, depends on you)

**Comment by zhicheng** [comment]
I'll look into it, thanks.

**Comment by 2000jedi** [comment]
# python:open/文件操作

open/文件操作
f=open('/tmp/hello','w')

#open(路径+文件名,读写模式)

#读写模式:r只读,r+读写,w新建(会覆盖原有文件),a追加,b二进制文件.常用模式

如:'rb','wb','r+b'等等

读写模式的类型有：

rU 或 Ua 以读方式打开, 同时提供通用换行符支持 (PEP 278)
w     以写方式打开，
a     以追加模式打开 (从 EOF 开始, 必要时创建新文件)
r+     以读写模式打开
w+     以读写模式打开 (参见 w )
a+     以读写模式打开 (参见 a )

**Comment by zhicheng** [comment]
fixed, os.open should like POSIX open not fopen.
