### ISSUE TITLE
.NET binding

### ISSUE THREAD

**Issue by cartman300** [lemon-lang/lemon#23]
![ham2kh](https://user-images.githubusercontent.com/3836060/32866268-299052f6-ca67-11e7-941b-0821d326cfbd.png)

Hello! I would like to say i discovered this language few days ago and instantly became a fan of it because it's easy to embed and not hard to learn.

I wanted to shout out here that i'm making a .NET binding for it because C# is my main language and i'd like to use this from time to time in some projects there.

https://github.com/cartman300/lemonade

The main repository is added as a submodule and compiles in visual studio just fine with some external supporting headers and without modifying the source code. 👍 

Also a side question, would it be possible to add a function similar to ``lemon_machine_execute`` and ``lemon_machine_execute_loop`` which only steps trough N machine instructions and returns back to the caller? I see this being useful when embedding the language into a video game update loop, it would prevent stuff like ``while (true) { }`` from hanging the game.

**Comment by zhicheng** [comment]
This is so cool, good job. about the step run, I'll add some debug utility in future, but I can't sure when.if you required this function right now,you can simple change source code of lemon, here is a quick demo patch.this may need some test, but enough for your test.

```
diff --git a/src/machine.c b/src/machine.c
index c6b8d54..4b7726e 100644
--- a/src/machine.c
+++ b/src/machine.c
@@ -1278,6 +1278,13 @@ lemon_machine_execute_loop(struct lemon *lemon)
 		CHECK_PAUSE(lemon->l_nil);
 	}
 	while (!machine->halt && machine->pc < machine->maxpc) {
+
+		if (machine->step >= 0) {
+			if (machine->step-- == 0) {
+				machine->step = 10;
+				return lemon->l_nil;
+			}
+		}
 		opcode = machine->code[machine->pc++];
 
 		switch (opcode) {
diff --git a/src/machine.h b/src/machine.h
index 9f1c8e6..61ed5c7 100644
--- a/src/machine.h
+++ b/src/machine.h
@@ -11,6 +11,7 @@ struct machine {
 	int fp; /* frame pointer */
 	int sp; /* stack pointer */
 
+	int step;
 	int halt;
 	int maxpc;
 
diff --git a/src/main.c b/src/main.c
index 23ea8f4..8b961e0 100644
--- a/src/main.c
+++ b/src/main.c
@@ -1,5 +1,6 @@
 #include "lemon.h"
 #include "shell.h"
+#include "machine.h"
 #include "larray.h"
 #include "lstring.h"
 #include "lib/builtin.h"
@@ -70,7 +71,15 @@ main(int argc, char *argv[])
 		}
 
 		lemon_machine_reset(lemon);
-		lemon_machine_execute(lemon);
+		struct machine *machine = lemon->l_machine;
+		machine->step = 10; // -1 for non-stop run
+		for (;;) {
+			printf("pc: %d\n", machine->pc);
+			lemon_machine_execute_loop(lemon);
+			if (machine->pc >= machine->maxpc) {
+				break;
+			}
+		}
 	}
 
 	lemon_destroy(lemon);

```
