### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by stefanos82** [lemon-lang/lemon#6]
First of all, great job; I love your coding style, it's super clean.

If I may, I would like to ask a couple of questions:

- What led you, frustrated you, or even motivated you to build a new language?
- What problems are you trying to solve?
- Is it GIL-free?
- Is it thread-safe by default?
- JIT support please?
- Any plans for generics support?

That's it for now.

Keep up the good work :+1:

**Comment by zhicheng** [comment]
glad you like Lemon, here is my answer.

1, What led you, frustrated you, or even motivated you to build a new language?
A: I use C Language in a lot of project,but C is lack a lot of feature in modern age, so I developed a new language that easy to fit in C.

2, What problems are you trying to solve?
A: 1, easily integrate with C. 2, stable and modern syntax. that's all I wanted.

3, Is it GIL-free?
A: Lemon is more like C, is C have GIL? no. is C have Thread? no. in Lemon, there's no thread and GIL such thing,It's just an ANSI C library.anything not in ANSI C will not in Lemon.

4, Is it thread-safe by default?
A: No, see 3.

5, JIT support please?
A: JIT is a good thing, I may or may not add JIT support.I also consider other JIT-like solution, such as translate Lemon to C.

6, Any plans for generics support?
A: have no idea what's generics is.Lemon is a dynamic type language.

feel welcome start topic in mailing-list https://groups.google.com/forum/#!forum/lemon-lang .

**Comment by ducdetronquito** [comment]
Hi @zhicheng !

Just discovered lemon a minute ago and I wanted to say that a Lemon to C compiler would be really awesome :)

**Comment by stefanos82** [comment]
I, as well, would like to see this translate-to-C option to be honest with you @zhicheng.

It would be very simple for me to translate existing Python code to Lemon and have the performance of C.

Just by thinking of this excites me :smile:

**Comment by zhicheng** [comment]
@stefanos82 Hi, the lemon-to-c translator is a long shot, I wouldn't count on it, at least I have no plan for that right now (I got the idea, but I just don't have time to implement it).

Also, if there is a lemon-to-c translator, It's can't get C level performance, very fast for sure, but still not fast like write in C(jit level speed give or take, maybe stable than jit). Just like C can't beat asm performance.

If you're interesting about compiler or generator. You can totally start by yourself, lemon source code is very readable,and the basic idea is translate the lemon bytecode to C. if you got any question just ask mailing list.
