### ISSUE TITLE
Possible bug inside lexer.c?

### ISSUE THREAD

**Issue by stefanos82** [lemon-lang/lemon#8]
@zhicheng Take a look at [src/lexer.c](https://github.com/lemon-lang/lemon/blob/master/src/lexer.c#L97) line 97.

What's that supposed to do? If it's checking for an octal, that code block should have been in line 94, correct?

**Comment by zhicheng** [comment]
Not exactly,
the `oct` == 1 mean we're in octal state, so if there '8' or '9' in the number, scan is done.'0' - '7' can in oct, dec and hex so they have a `break`.
